### ISSUE TITLE
getting this error in pycharm please help!

### ISSUE THREAD

**Issue by mohsinogen** [sahil-rajput/Candice#2]
Traceback (most recent call last):
  File "C:/Users/Acer/Desktop/Robin/app.py", line 9, in <module>
    bot = ChatBot("Candice")
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\chatterbot-1.1.0a7-py3.8.egg\chatterbot\chatterbot.py", line 28, in __init__
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\chatterbot-1.1.0a7-py3.8.egg\chatterbot\utils.py", line 33, in initialize_class
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\chatterbot-1.1.0a7-py3.8.egg\chatterbot\storage\sql_storage.py", line 20, in __init__
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\chatterbot-1.1.0a7-py3.8.egg\chatterbot\storage\storage_adapter.py", line 22, in __init__
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\chatterbot-1.1.0a7-py3.8.egg\chatterbot\tagging.py", line 20, in __init__
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy-2.1.9-py3.8-win-amd64.egg\spacy\__init__.py", line 10, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
ModuleNotFoundError: No module named 'thinc'

**Comment by sahil-rajput** [comment]
pip install thinc
