### ISSUE TITLE
1 of 119 Issue while running the python app.py chatbot file using flask query

### ISSUE THREAD

**Issue by Samiksha-khandelwal** [sahil-rajput/Candice#4]
While running the python chatter code using flask was facing the below issue,

"C:\Users\Lenovo\PycharmProjects\new bot\venv\Scripts\python.exe" "C:/Users/Lenovo/PycharmProjects/new bot/app.py"
Traceback (most recent call last):
  File "C:/Users/Lenovo/PycharmProjects/new bot/app.py", line 9, in <module>
    bot = ChatBot("DTAG")
  File "C:\Users\Lenovo\PycharmProjects\new bot\venv\lib\site-packages\chatterbot\chatterbot.py", line 28, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\Lenovo\PycharmProjects\new bot\venv\lib\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(*args, **kwargs)
  File "C:\Users\Lenovo\PycharmProjects\new bot\venv\lib\site-packages\chatterbot\storage\sql_storage.py", line 20, in __init__
    super().__init__(**kwargs)
  File "C:\Users\Lenovo\PycharmProjects\new bot\venv\lib\site-packages\chatterbot\storage\storage_adapter.py", line 23, in __init__
    'tagger_language', languages.ENG
  File "C:\Users\Lenovo\PycharmProjects\new bot\venv\lib\site-packages\chatterbot\tagging.py", line 20, in __init__
    import spacy
  File "C:\Users\Lenovo\PycharmProjects\new bot\venv\lib\site-packages\spacy\__init__.py", line 12, in <module>
    from .cli.info import info as cli_info
  File "C:\Users\Lenovo\PycharmProjects\new bot\venv\lib\site-packages\spacy\cli\__init__.py", line 6, in <module>
    from .train import train  # noqa: F401
  File "C:\Users\Lenovo\PycharmProjects\new bot\venv\lib\site-packages\spacy\cli\train.py", line 18, in <module>
    from ..gold import GoldCorpus
  File "strings.pxd", line 23, in init spacy.gold
ImportError: DLL load failed: The specified module could not be found.

Process finished with exit code 1

Could you please help me to resolve these.

**Comment by sahil-rajput** [comment]
https://stackoverflow.com/questions/20201868/importerror-dll-load-failed-the-specified-module-could-not-be-found
